# postgresql
# Build using: docker build -t "postgresql:0.0.1" --rm=true --no-cache .
#
# NAME             postgresql
# VERSION          0.0.1
# LAST_UPDATED     2016-08-03

FROM     ubuntu:14.04
MAINTAINER Radhakrishna Nayak "nayak.radhakrishna@gmail.com"

RUN  apt-get update \
  && apt-get -y upgrade \
  && apt-get -y install vim
RUN apt-get -y install postgresql-9.3
